### ISSUE TITLE
百度小程序一直不停的route和连接！

### ISSUE THREAD

**Issue by xztl** [wildfirechat/uni-chat-demo#1]
![image](https://user-images.githubusercontent.com/11171790/147181728-d7d6d209-e856-4b5a-b851-e178ff81d8a2.png)
![image](https://user-images.githubusercontent.com/11171790/147181743-979aa8f9-a0bc-49ea-b243-7aaedd0fb3cf.png)
![image](https://user-images.githubusercontent.com/11171790/147181760-33552776-c658-4d5e-b2cd-32728b284569.png)
复现：断网后重连偶现，点击百度开发工具的刷新后，重新登录进入是必现
![image](https://user-images.githubusercontent.com/11171790/147181820-a2bda7d5-efdf-46ad-ad5c-2bfc8cc3a289.png)

**Comment by xztl** [comment]
怀疑是百度小程序机制问题：
![image](https://user-images.githubusercontent.com/11171790/147194920-e4c5e7ba-0804-4655-9571-1406d2baa7d7.png)

**Comment by heavyrain2012** [comment]
小程序SDK需要购买，购买后才可以使用
